version: '3'
services:
  app:
    build: .
    command: sh -c "flask run --host=0.0.0.0 --port=5000"
    environment:
      APP_MONGO_URI: mongodb://mongo:27017/utair
      APP_REDIS_URI: redis://redis:6379/10
      APP_LOGIN: admin
      APP_PASSWORD: admin
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  test:
    build: .
    command: sh -c "pip install -e .[test] && pytest"
    environment:
      APP_MONGO_URI: mongodb://mongo:27017/utair_test
      APP_REDIS_URI: redis://redis:6379/11
      APP_LOGIN: admin
      APP_PASSWORD: admin
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
